# Generated by Django 6.1 on 2026-09-06 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('velocity', 'Velocity Spike'), ('geo', 'Geographic Anomaly'), ('device', 'New Device'), ('amount', 'Amount Deviation'), ('auth', 'Authentication Failure'), ('time', 'Unusual Time'), ('channel', 'Channel Mismatch'), ('custom', 'Custom Rule')], default='custom', max_length=16)),
                ('threshold', models.FloatField(default=70.0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_masked', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('nri', 'NRI'), ('fd', 'Fixed Deposit')], default='savings', max_length=16)),
                ('risk_score', models.IntegerField(default=0)),
                ('recent_tx_count', models.IntegerField(default=0)),
                ('fraud_alerts_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='FraudTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('account_masked', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('channel', models.CharField(choices=[('Mobile API', 'Mobile API'), ('Web Banking', 'Web Banking'), ('ATM', 'ATM'), ('Branch', 'Branch'), ('POS', 'POS'), ('UPI', 'UPI')], default='Mobile API', max_length=32)),
                ('merchant', models.CharField(max_length=128)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('HELD', 'Held'), ('BLOCKED', 'Blocked'), ('ALLOWED', 'Allowed'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=16)),
                ('prediction', models.CharField(default='LEGITIMATE', max_length=16)),
                ('model_confidence', models.FloatField(default=0.0)),
                ('fraud_type', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fraud Transaction',
                'verbose_name_plural': 'Fraud Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='CNN-BiLSTM', max_length=64)),
                ('version', models.CharField(default='v3.2.1', max_length=16)),
                ('accuracy', models.FloatField(default=97.3)),
                ('precision', models.FloatField(default=96.1)),
                ('recall', models.FloatField(default=95.8)),
                ('f1_score', models.FloatField(default=95.9)),
                ('auc_roc', models.FloatField(default=0.9847)),
                ('throughput', models.IntegerField(default=847)),
                ('avg_latency_ms', models.IntegerField(default=12)),
                ('queue_size', models.IntegerField(default=3)),
                ('total_predictions_today', models.IntegerField(default=12847)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Metrics',
                'verbose_name_plural': 'Model Metrics',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=64)),
                ('transaction_id', models.CharField(blank=True, max_length=32)),
                ('case_id', models.CharField(blank=True, max_length=32)),
                ('result', models.CharField(default='Successful', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=32, unique=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=10)),
                ('title', models.CharField(max_length=256)),
                ('account', models.CharField(max_length=32)),
                ('transactions_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShapFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=64)),
                ('contribution_pct', models.FloatField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shap_features', to='soc.fraudtransaction')),
            ],
            options={
                'ordering': ['-contribution_pct'],
            },
        ),
    ]
