# Generated by Django 6.1.1 on 2026-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.RemoveField(
            model_name='shapfeature',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='ModelMetrics',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='securitycase',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='securitycase',
            name='transactions_count',
        ),
        migrations.AddField(
            model_name='securitycase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='securitycase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=16),
        ),
        migrations.DeleteModel(
            name='FraudTransaction',
        ),
        migrations.DeleteModel(
            name='ShapFeature',
        ),
    ]
